sudo: required
# Because we are using docker

services:
  - docker
  # Travis install a copy of docker

before_install:
  - docker build -t gustavosr98/curso-docker-travisci -f Dockerfile.dev .
  # Test container build

script:
  - docker run gustavosr98/curso-docker-travisci npm run test -- --coverage
  # Excute tests
