version: '3'
services:
  frontend:
    build:
      # Using named dockerfile
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Kind of like reference pointers to files
      # Used to be able to do hotreloading while developing
      - /app/node_modules # Bookmark - Only on container
      - .:/app # Reference from local machine to container
  test:
    # Alternative solution to run test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # Bookmark - Only on container
      - .:/app # Reference from local machine to container
    command: ["npm", "run", "test"]